version: '3.1'
services:

  elixir:
    build: ./app
    ports:
      - 4000:4000
    volumes:
      - ./app:/app
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD : ${POSTGRES_PASSWORD}
      POSTGRES_USER : ${POSTGRES_USER}
      POSTGRES_DB : ${POSTGRES_DB}
  
  adminer:
    image: adminer
    ports:
      - 8080:8080

volumes:
    db_data: